// UrasandesuPrig.idl : Urasandesu.Prig の IDL ソース
//

// このファイルは、タイプ ライブラリ (UrasandesuPrig.tlb) およびマーシャリング コードを
// 作成するために MIDL ツールによって処理されます。

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(9D7CB40B-03CE-4B6A-87D8-9B332CBDFCC0),
	version(1.0),
]
library UrasandesuPrigLib
{
	importlib("stdole2.tlb");
};

