/* 
 * File: ULTableMixinTest.cs
 * 
 * Author: Akira Sugiura (urasandesu@gmail.com)
 * 
 * 
 * Copyright (c) 2014 Akira Sugiura
 *  
 *  This software is MIT License.
 *  
 *  Permission is hereby granted, free of charge, to any person obtaining a copy
 *  of this software and associated documentation files (the "Software"), to deal
 *  in the Software without restriction, including without limitation the rights
 *  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *  copies of the Software, and to permit persons to whom the Software is
 *  furnished to do so, subject to the following conditions:
 *  
 *  The above copyright notice and this permission notice shall be included in
 *  all copies or substantial portions of the Software.
 *  
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 *  THE SOFTWARE.
 */


using NUnit.Framework;
using program1.MyLibrary;
using System;
using System.Collections;
using System.Prig;
using UntestableLibrary.Prig;
using Urasandesu.Prig.Framework;
using program1.Mixins.UntestableLibrary;
using UntestableLibrary;

namespace Test.program1.Mixins.UntestableLibrary
{
    [TestFixture]
    public class ULTableMixinTest
    {
        [Test]
        public void GetAutoGeneratedColumns_should_return_columns_that_are_auto_generated()
        {
            using (new IndirectionsContext())
            {
                // Arrange
                PULColumns.ValidateStateULTableStatus().Body = args => null;
                
                var expected = new[] { new ULColumn("USER_ID"), new ULColumn("DELETED"), new ULColumn("CREATED"), new ULColumn("MODIFIED") };
                var users = new ULTable("USER");
                users.Columns.Add(expected[0]);
                users.Columns.Add(new ULColumn("PASSWORD"));
                users.Columns.Add(new ULColumn("USER_NAME"));
                users.Columns.Add(expected[1]);
                users.Columns.Add(expected[2]);
                users.Columns.Add(expected[3]);
                
                
                // Act
                var actual = users.GetAutoGeneratedColumns();

                
                // Assert
                CollectionAssert.AreEqual(expected, actual);
            }
        }

        [Test]
        public void GetManuallyGeneratedColumns_should_return_columns_that_are_manually_generated()
        {
            using (new IndirectionsContext())
            {
                // Arrange
                PULColumns.ValidateStateULTableStatus().Body = args => null;

                var expected = new[] { new ULColumn("PASSWORD"), new ULColumn("USER_NAME") };
                var users = new ULTable("USER");
                users.Columns.Add(new ULColumn("USER_ID"));
                users.Columns.Add(expected[0]);
                users.Columns.Add(expected[1]);
                users.Columns.Add(new ULColumn("DELETED"));
                users.Columns.Add(new ULColumn("CREATED"));
                users.Columns.Add(new ULColumn("MODIFIED"));


                // Act
                var actual = users.GetManuallyGeneratedColumns();


                // Assert
                CollectionAssert.AreEqual(expected, actual);
            }
        }
    }
}
